### ISSUE TITLE
[DELETED/DUPLICATE] Display bill total

### ISSUE THREAD

**Issue by lynnozhang7** [cs130-w21/dots-ios#19]
## User Story
As a user, I would like to see the total of the bill clearly, so that I can know how much was spent and confirm that the item entries were added correctly. 

## Detailed Description
This total should be obtained by adding all of the item entries in the bill.

**Comment by JackZhao98** [comment]
Combined into a new story. Issue closed.

**Comment by JackZhao98** [comment]
Bill reopened.
