### ISSUE TITLE
Adding Group Members

### ISSUE THREAD

**Issue by GMA5566** [cs130-w21/dots-ios#5]
## User Story
As a user, I would like to add group members before I add any receipts without the hassle of having to write down their names one by one, so that I can save my time and privacy.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [x] Given **[Condition]**, then **[Expected Result]**
- [x] Given **[Condition]**, then **[Expected Result]**
- [x] Given **[Condition]**, then **[Expected Result]**

**Comment by JackZhao98** [comment]
Group members can now be added with the colored wheel. Issue closed
