### ISSUE TITLE
Number of Group Members

### ISSUE THREAD

**Issue by GMA5566** [cs130-w21/dots-ios#6]
## User Story
As a user, I would like to have the App indicate the number of group members after I added all of them, so that I can confirm my selections.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [x] Given **[Condition]**, then **[Expected Result]**
- [x] Given **[Condition]**, then **[Expected Result]**
- [x] Given **[Condition]**, then **[Expected Result]**

**Comment by JackZhao98** [comment]
Can be added at anytime. Not necessary at this moment. issue closed.

**Comment by JackZhao98** [comment]
Removed feature
