### ISSUE TITLE
Enable Face ID

### ISSUE THREAD

**Issue by GMA5566** [cs130-w21/dots-ios#75]
## User Story
As a user, I would like to be able to log in using my Face ID, so that I can both login quickly and have my data protected.

## Detailed Description
Use faceid / touchid to protect user's data

## Acceptance Criteria
- [x] Given **enable faceid**, then **Lock Screen every time the user exit the app**
- [x] Given **correct faceid**, then **unlock the main screen**
- [x] Given **incorrect faceid**, then **keep the blur layer on the main screen and prompt user to scan again**

**Comment by JackZhao98** [comment]
Direct commit to master, oops

d602a5b89df4db2db9b37c7d217848cab9bea3f5
